services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "8080:8080" # Traefik dashboard
      - "5055:5055" # Traccar Teltonika protocol
      - "5027:5027" # Traccar H02 protoco
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-data:/etc/traefik
    command:
      - "--api.insecure=true"  # Enable dashboard (insecure, for development only)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traccar-teltonika.address=:5055"  # New TCP entrypoint for 5055
      - "--entrypoints.traccar-h02.address=:5027"       # New TCP entrypoint for 5027
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=c.morgenthaler@morgenthaler-de.com"  # Replace with your email
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`ingress.socratec.gmbh`)"  # Replace with your domain
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal"

  postgres:
    image: postgres:15
    container_name: traccar-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=traccar
      - POSTGRES_PASSWORD=traccar_password  # Change this to a secure password
      - POSTGRES_DB=traccar
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traccar"]
      interval: 10s
      timeout: 5s
      retries: 5

  traccar:
    image: ghcr.io/socratec-telematic-gmbh/traccar-docker:latest
    container_name: traccar
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - traccar-config:/opt/traccar/conf
      - traccar-data:/opt/traccar/data
      - traccar-logs:/opt/traccar/logs
    environment:
      - TRACCAR_DB_HOST=postgres
      - TRACCAR_DB_PORT=5432
      - TRACCAR_DB_NAME=traccar
      - TRACCAR_DB_USER=traccar
      - TRACCAR_DB_PASSWORD=traccar_password  # Match with POSTGRES_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traccar.rule=Host(`smc.socratec.gmbh`)"  # Replace with your domain
      - "traefik.http.routers.traccar.entrypoints=websecure"
      - "traefik.http.routers.traccar.tls.certresolver=myresolver"
      - "traefik.http.services.traccar.loadbalancer.server.port=8082"  # Traccar web interface port
      # TCP router for Teltonika (5055)
      - "traefik.tcp.routers.traccar-teltonika.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.traccar-teltonika.entrypoints=traccar-teltonika"
      - "traefik.tcp.services.traccar-teltonika.loadbalancer.server.port=5055"
      # TCP router for H02 (5027)
      - "traefik.tcp.routers.traccar-h02.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.traccar-h02.entrypoints=traccar-h02"
      - "traefik.tcp.services.traccar-h02.loadbalancer.server.port=5027"
volumes:
  traefik-data:
  postgres-data:
  traccar-config:
  traccar-data:
  traccar-logs:

networks:
  default:
    name: traccar-network
