services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      #- "1883:1883" # MQTT
      - "8080:8080" # Traefik dashboard
      - "5055:5055" # Traccar Teltonika protocol
      - "5027:5027" # Traccar H02 protoco
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-data:/etc/traefik
    command:
      - "--api.insecure=true"  # Enable dashboard (insecure, for development only)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traccar-teltonika.address=:5055"
      - "--entrypoints.traccar-h02.address=:5027"
      #- "--entrypoints.traccar-mqtt.address=:1883"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=c.morgenthaler@morgenthaler-de.com"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`ingress.socratec.gmbh`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal"

  postgres:
    image: postgres:15
    container_name: traccar-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=traccar
      - POSTGRES_PASSWORD=traccar_password
      - POSTGRES_DB=traccar
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traccar"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      
  traccar:
    image: ghcr.io/socratec-telematic-gmbh/traccar-docker:latest
    container_name: traccar
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "1883:1883"
      - "5001-5026:5001-5026"
      - "5028-5054:5028-5054"
      - "5056-5200:5056-5200"
    volumes:
      - traccar-config:/opt/traccar/conf
      - traccar-data:/opt/traccar/data
      - traccar-logs:/opt/traccar/logs
    environment:
      - TRACCAR_DB_HOST=postgres
      - TRACCAR_DB_PORT=5432
      - TRACCAR_DB_NAME=traccar
      - TRACCAR_DB_USER=traccar
      - TRACCAR_DB_PASSWORD=traccar_password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traccar.rule=Host(`smc.socratec.gmbh`)"
      - "traefik.http.routers.traccar.entrypoints=websecure"
      - "traefik.http.routers.traccar.tls.certresolver=myresolver"
      - "traefik.http.routers.traccar.service=traccar-web"
      - "traefik.http.services.traccar-web.loadbalancer.server.port=8082"
      # TCP router and service for Teltonika (5055)
      - "traefik.tcp.routers.traccar-teltonika.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.traccar-teltonika.entrypoints=traccar-teltonika"
      - "traefik.tcp.routers.traccar-teltonika.service=traccar-teltonika-svc"
      - "traefik.tcp.services.traccar-teltonika-svc.loadbalancer.server.port=5055"
      # TCP router and service for H02 (5027)
      - "traefik.tcp.routers.traccar-h02.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.traccar-h02.entrypoints=traccar-h02"
      - "traefik.tcp.routers.traccar-h02.service=traccar-h02-svc"
      - "traefik.tcp.services.traccar-h02-svc.loadbalancer.server.port=5027"
      # MQTT (1883)
      #- "traefik.tcp.routers.traccar-mqtt.rule=HostSNI(`*`)"
      #- "traefik.tcp.routers.traccar-mqtt.entrypoints=traccar-h02"
      #- "traefik.tcp.routers.traccar-mqtt.service=traccar-h02-svc"
      #- "traefik.tcp.services.traccar-mqtt-svc.loadbalancer.server.port=1883"
  traccar-forwarder:
    image: ghcr.io/socratec-telematic-gmbh/traccar-forwarder:latest
    container_name: traccar-forwarder
    restart: unless-stopped
    volumes:
      - traccar-forwarder-conf:/app/appsettings.json
      - traccar-forwarder-state:/app/state
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
volumes:
  traefik-data:
  postgres-data:
  traccar-config:
  traccar-data:
  traccar-logs:
  traccar-forwarder-conf:
  traccar-forwarder-state:
  pgadmin-data:

networks:
  default:
    name: traccar-network
