---
name: Build and push docker image

env:
  GITHUB_REPOSITORY: socratec/traccar

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+

defaults:
  run:
    shell: bash

jobs:
  docker-build-push:
    name: Build and push docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os: [alpine, debian, ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set environment GITHUB_IMAGE_TAGS on master
        if: github.ref == 'refs/heads/master' && matrix.os == 'alpine'
        run: |
          _REPO=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
          echo "GITHUB_IMAGE_TAGS=ghcr.io/${_REPO}:latest" >> $GITHUB_ENV
      - name: Set environment GITHUB_IMAGE_TAGS
        if: github.ref != 'refs/heads/master'
        run: |
          _REPO=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
          _BRANCH=${GITHUB_REF##*/}
          _VERSION=${_BRANCH#v*}
          _MAJOR_VERSION=${_VERSION%.*}
          _BASE_TAG="ghcr.io/${_REPO}"
          _GITHUB_IMAGE_TAGS="$_BASE_TAG:$_VERSION-${{ matrix.os }}"
          _GITHUB_IMAGE_TAGS+=",$_BASE_TAG:$_MAJOR_VERSION-${{ matrix.os }}"
          _GITHUB_IMAGE_TAGS+=",$_BASE_TAG:${{ matrix.os }}"
          if [ "${{ matrix.os }}" == "alpine" ]; then
            _GITHUB_IMAGE_TAGS+=",$_BASE_TAG:$_VERSION"
            _GITHUB_IMAGE_TAGS+=",$_BASE_TAG:$_MAJOR_VERSION"
          fi
          echo "GITHUB_IMAGE_TAGS=$_GITHUB_IMAGE_TAGS" >> $GITHUB_ENV
      - name: Set environment GITHUB_IMAGE_PLATFORMS
        run: |
          _GITHUB_IMAGE_PLATFORMS="linux/amd64,linux/arm64"
          if [ "${{ matrix.os }}" == "ubuntu" ]; then
            _GITHUB_IMAGE_PLATFORMS+=",linux/arm/v7"
          fi
          echo "GITHUB_IMAGE_PLATFORMS=$_GITHUB_IMAGE_PLATFORMS" >> $GITHUB_ENV
      - name: Build and push
        if: env.GITHUB_IMAGE_TAGS != ''
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.${{ matrix.os }}
          tags: ${{ env.GITHUB_IMAGE_TAGS }}
          platforms: ${{ env.GITHUB_IMAGE_PLATFORMS }}
          push: true

